apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: dcp-agones-simple-fleet
spec:
  replicas: 2
  scheduling: Distributed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        foo: bar
    spec:
      ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 6969
        protocol: UDP
      health:
        disabled: false
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
      sdkServer:
        logLevel: Info
      template:
        spec:
          containers:
          - name: dcp-agones-simple-server
            image: gcr.io/drift-car-party-demo/nubrazz/dcp:3.9
          resources:
            requests:
              memory: "400M"
              cpu: "100m"
            limits:
              memory: "400M"
              cpu: "100m"
