apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: dcp-agones-simple-fleetautoscaler
spec:
  fleetName: dcp-agones-simple-fleet
  policy:
    type: Buffer
    buffer:
      bufferSize: 5
      minReplicas: 10
      maxReplicas: 20
  sync:
    type: FixedInterval
    fixedInterval:
      seconds: 30
