apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "dcp-agones-simple-server-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7770
    protocol: UDP
  health:
    disabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3
  template:
    spec:
      containers:
      - name: dcp-agones-simple-server
        image: gcr.io/agones-training-3/nubrazz/dcp:1.7
      resources:
        requests:
          memory: "128Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "128m"
