apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "dcp-agones-simple-server-"
spec:
  ports:
  - name: default
    portPolicy: Static
    containerPort: 7934
    hostPort: 7777
    protocol: UDP
  health:
    disabled: false
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3
  template:
    spec:
      containers:
        - name: dcp-agones-simple-server
          image: gcr.io/drift-car-party-demo/nubrazz/dcp:4.3
      resources:
        requests:
          memory: "400M"
          cpu: "100m"
        limits:
          memory: "400M"
          cpu: "100m"
